dependencies {
    api project(":core:widgettree")
    api project(":geom")
    implementation project(":graphics") // PointerStateDependentImpl miatt
    testImplementation project(":desktop")
    testImplementation project(":platform:awt")
    testImplementation project(":text")
    testImplementation project(":layout-model")
    testImplementation project(":layout-constraint")
}
