rootProject.name = "ui11"

include "ui-animation"
include "ui-audio"
include "ui-base"
include "ui-css"
include "ui-desktop"
include "ui-document"
include "ui-geom"
include "ui-graphics"
include "ui-input"
include "ui-layout-constraint"
include "ui-layout-model"
include "ui-controls"
include "ui-controls-defaultlook"
include "ui-lottie"
include "ui-lottie-web"
include "ui-media"
include "ui-platform-awt"
include "ui-platform-dom"
include "ui-text"
include "ui-webcontent"
include "observable"
include "reflectutil"