rootProject.name = "ui11"

include "animation"
include "asset-reference-generator"
include "audio"
include "base"
include "color"
include "controls"
include "controls-defaultlook"
include "css"
include "desktop"
include "designtokens-model"
include "geom"
include "graphics"
include "i18n"
include "input"
include "imageio"
include "layout-constraint"
include "layout-model"
include "layout-opt"
include "live-localization-editor"
include "lottie-web"
include "media"
include "observable"
include "platform-awt"
include "platform-dom"
include "platform-glass"
include "renderer-java2d"
include "renderer-opengles"
include "reflectutil"
include "task"
include "text"
include "webcontent"