rootProject.name = "ui11"

include "animation"
include "audio"
include "base"
include "css"
include "desktop"
include "document"
include "geom"
include "graphics"
include "input"
include "layout-constraint"
include "layout-model"
include "controls"
include "controls-defaultlook"
include "lottie"
include "media"
include "observable"
include "platform:awt"
include "platform:dom"
include "platform:lottie-web"
include "reflectutil"
include "text"
include "webcontent"
