dependencies {
    api project(":ui-base")
    implementation project(":ui-graphics")

    implementation "org.teavm:teavm-interop:${teavmVersion}" // hogy DefaultURLImageView-t letilthassuk
    implementation "org.teavm:teavm-metaprogramming-api:${teavmVersion}" // ImageResourceAnnotationHandler miatt
}
