plugins {
    id 'java-library'
}

dependencies  {
    api project(":observable")

    implementation project(":reflectutil")
    implementation "org.teavm:teavm-metaprogramming-api:${teavmVersion}"
    implementation "org.teavm:teavm-metaprogramming-impl:${teavmVersion}" // ListenerProxyTeaVMSupport::teavmClassToType
    implementation "org.teavm:teavm-interop:${teavmVersion}"
    implementation "org.teavm:teavm-core:${teavmVersion}" // RememberedValueTeaVMPlugin
    implementation "org.teavm:teavm-jso-apis:${teavmVersion}" // TeaVMWidgetAccessor
    implementation "org.teavm:teavm-jso-impl:${teavmVersion}" // JSWrapper
    implementation "org.teavm:teavm-platform:${teavmVersion}" // PlatformMarker
    implementation "org.ow2.asm:asm:9.6"

    testImplementation 'org.openjdk.jmh:jmh-core:1.18';
    testImplementation 'org.openjdk.jmh:jmh-generator-annprocess:1.18';
    testImplementation project(":layout-constraint")
    testImplementation project(":platform-awt")
    testImplementation project(":renderer-java2d")
}
