dependencies {
    api project(":ui-base")
    api project(":ui-geom")
    implementation project(":ui-graphics") // PointerStateDependentImpl miatt
    testImplementation project(":ui-desktop")
    testImplementation project(":ui-platform-awt")
    testImplementation project(":ui-text")
    testImplementation project(":ui-layout-model")
    testImplementation project(":ui-layout-constraint")
}
