dependencies {
    api project(":controls")
    api project(":css")
    implementation project(":desktop") // link megnyitás miatt
    implementation project(":input")

    testImplementation project(":platform-awt")
    testImplementation project(":renderer-java2d")
    testImplementation project(":layout-constraint")
}