plugins {
    id 'java-library'
}

dependencies  {
    // TODO api project(":ui")
    api "org.teavm:teavm-jso-apis:${teavmVersion}"

    api project(":ui-base")
    implementation project(":ui-audio") // ez lehetne külön modulba
    implementation project(":ui-controls")
    implementation project(":ui-css")
    implementation project(":ui-document")
    api project(":ui-desktop") // DOMEnvironment implements Shell, ezért muszáj API dependencynek lennie
    implementation project(":ui-text")
    implementation project(":ui-webcontent")
    implementation project(":ui-media")
    //implementation project(":ui-css-inline")
    api project(":ui-animation") // DOMEnvironment implements Scheduler, ezért muszáj API dependencynek lennie
}
